- name: Copy docker compose 
  copy:
    src: /Users/irschad/java-mysql-project/docker-compose-full.yaml
    dest: /home/irschad/docker-compose.yaml

- name: Docker login
  docker_login:
    username: irschad
    password: "{{docker_password}}"

- name: Start containers from compose
  community.docker.docker_compose_v2:
    project_src: /home/irschad